app/urls.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.urls import path
from app.views import * 

app_name = 'app'

urlpatterns = [
    path('portal', never_cache(Portal.as_view()), name="portal"),
    path('pay', Pay.as_view()),
    path('slot', Slot.as_view()),
    path('commit', Commit.as_view()),
    path('browse', Browse.as_view()),
    path('pause', Pause.as_view()),
    path('gen_rc', GenerateRC.as_view()),
    path('activate', ActivateDevice.as_view()),
    path('sweep', Sweep.as_view()),
    path('voucher', GenerateVoucher.as_view()),
    path('redeem', Redeem.as_view()),
    path('eload', EloadPortal.as_view())
]

opw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

from django.conf.urls.static import static
from django.conf import settings

from .views import * 

urlpatterns = [
    path('app/', include('app.urls')),
    path('app/admin/', admin.site.urls),
    path('app/api/', include('app.api.urls')),
    path('', RedirectView.as_view(url='/app/portal')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/base_control.html
<!DOCTYPE html>
<html>
    {% block head %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        {% block title %}<title>{{ hotspot }}</title> {% endblock title %}
        <!-- Bootstrap css -->
        <link rel="stylesheet" href="/static/vendors/bootstrap-4.1.1/dist/css/bootstrap.min.css">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="/static/build/css/control.css">
        <!-- Fontawesome CSS -->
        <link rel="stylesheet" href="/static/vendors/fontawesome-free-5.4.1-web/css/all.css">
    </head>
    {% endblock head %}
    {% block body %}
    <body>
        <div class="wrapper">
            {% block sidebar %}
            {% endblock sidebar %}
            {% block content %}
            <div id="content">
                {% block navbar %}
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <!-- <div class="container-fluid"> -->
                        <button type="button" id="sidebarCollapse" class="btn btn-info ml-2">
                            <i class="fas fa-align-left"></i>
                        </button>
                        <a class="navbar-brand ml-2" href="#">Control Panel</a>
                        <button type="button" class="btn btn-dark d-inline-block d-lg-none ml-auto ml-2" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fas fa-align-justify"></i>
                        </button>
                        
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto">
                              <li class="nav-item">
                                <a class="nav-link" href="{% url 'app:portal' %}">
                                  <i class="fas fa-external-link-alt"></i> Main Portal</a>
                              </li>  
                              <li class="nav-item dropdown">
                                <button class="btn btn-primary" type="button" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                                  aria-haspopup="true" aria-expanded="false">
                                  <span class="fas fa-user"></span> {{ user.get_username }} </a>
                                </button>
                                <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
                                  <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Settings</a>
                                  <a class="dropdown-item" href="{% url 'admin:logout' %}">Log out</a>
                                </div>
                              </li>
                            </ul>
                      </div>
                    <!-- </div> -->
                </nav>
                {% endblock navbar %}
                {% block main %}
                
                {% endblock main %}
            </div>
            {% endblock content %}
        </div>
        {% block main_scripts %}
        <!-- JQuery -->
        <script src="/static/vendors/jquery-3.3.1/jquery.js"></script>
        <!-- Bootstrap JS -->
        <script src="/static/vendors/bootstrap-4.1.1/dist/js/bootstrap.bundle.min.js"></script>
        {% endblock main_scripts %}
        {% block custom_scripts %} 
        {% endblock custom_scripts %}
    </body>
    {% endblock body %}
</html>

app/templates/base_site.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        {% block meta %}
            <!-- Required meta tags -->
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1"> 
            <!-- , shrink-to-fit=no -->
        {% endblock meta %}

        <title>{% block title %}{% endblock title %}</title>
        <link rel="shortcut icon" href="/static/build/images/favicon.ico">

        {% block stylesheets %}
            <!-- Bootstrap CSS -->
            <link rel="stylesheet" href="/static/vendors/bootstrap-4.1.1/dist/css/bootstrap.min.css">

            <!--Material Design Bootstrap-->
            <link rel="stylesheet" href="/static/vendors/mdb-free_4.5.12/css/mdb.min.css" >

             <!--Fontawesome CSS-->
            <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
            <link rel="stylesheet" href="/static/vendors/fontawesome-free-5.4.1-web/css/all.css">
            <!--<link rel="stylesheet" href="/static/vendors/fontawesome-free-5.1.0-web/css/brands.css">-->

            <!-- Custom CSS -->
            <link rel="stylesheet" href="/static/build/css/custom.css">

            <!--PNotify CSS-->
            <link rel="stylesheet" href="/static/build/css/pnotify.custom.min.css">

            <!--Animate CSS-->
            <link rel="stylesheet" href="/static/build/css/animate.css">
        {% endblock stylesheets %}

    {% endblock head %}
</head>
<body class="bg-dark">
{% block body %}
    {% block top_navigation %}
    {% endblock top_navigation %}
    {% block content %}
    {% endblock content %}

{% endblock body %}

{% block javascripts %}

{% endblock javascripts %}
</body>
</html>

app/templates/eload_portal.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OJO PISOWIFI - ELoad</title>
    <link rel="stylesheet" href="/static/vendors/bulma-0.7.5/css/bulma.min.css">
    <script defer src="/static/vendors/fontawesome-free-5.4.1-web/js/all.js"></script>
  </head>
  <body>
   <section class="section">
   		<div class="container">
   			<div class="field">
			  <label class="label">Network</label>
			  <div class="control">
			    <div class="select">
			      <select>
			        <option>Smart</option>
			        <option>Globe</option>
			        <option>Sun</option>
			      </select>
			    </div>
			  </div>
			</div>

		    <div class="field">
			  <label class="label">Phone Number</label>
			  <div class="control">
			    <input class="input" type="text" placeholder="09xxxxxxxxx">
			  </div>
			</div>

			<div class="field">
			  <label class="label">Denomination</label>
			  <div class="control has-icons-left has-icons-right">
			    <input class="input is-success" type="text" placeholder="1-150">
			    <span class="icon is-small is-left">
			      <i class="fas fa-user"></i>
			    </span>
			    <span class="icon is-small is-right">
			      <i class="fas fa-check"></i>
			    </span>
			  </div>
			  <p class="help is-success">This username is available</p>
			</div>

			<div class="field">
			  <div class="control">
			    <label class="checkbox">
			      <input type="checkbox">
			      Pay through cashier/teller
			    </label>
			  </div>
			</div>

			<div class="field is-grouped">
			  <div class="control">
			    <button class="button is-link">Buy Load</button>
			  </div>
			</div>
		</div>
		<div class="container"></div>
	</section>
  </body>
</html>

app/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
    {% csrf_token %}
</body>
</html>

app/templates/footer.html
<div class="row">
    <div class="col-sm">
        JJM Rent a Car
    </div>
    <div class="col-sm text-right">
        KANDING Software Solutions
    </div>
</div>

app/templates/ftp.html
{% extends "base_site.html" %}
{% block content%}
    <div class="row">
        <div class="col-sm-3">
            <form class="form-horizontal form-label-left" method="post" id="FtpConnectForm" action="">
                {% csrf_token %}
                {% for field in FtpConnectForm %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">Connect</button>
            </form>
        </div>
        <div class="col">
            <ul>
            {% for line in dir_contents %}
                <a href="{{ line.name }}{% if line.type == 'dir' %}/{% endif %}">{{ line.name }}</a>
            {% endfor %}
            </ul>
            <br>
            <ul>
            {% for line in error %}
                <li>{{ line }}</li>
            {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

app/templates/hello.html
Hello World

app/templates/index.html
{% extends "base_site.html" %}

{% block title %} BI Central {% endblock title %}

{% block body %}
    {% block top_navigation %}
        <div class="top_nav">
          {% include "top_navigation.html" %}
        </div>
    {% endblock top_navigation %}

    {% block content %}
            <div class="row">
                <div class="col">

                </div>
                <div class="col">

                </div>
                <div class="col">

                </div>
            </div>
    {% endblock content %}
{% endblock body %}

app/templates/settings_update.html
{% extends "control.html" %}

{% block main %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save Changes">
</form>
{% endblock main %}

app/templates/singleton_change_form.html
{% extends "admin/change_form.html" %}
{% load i18n %}
{% load admin_urls %}

{% block breadcrumbs %}

<ol class="breadcrumb float-sm-right">
    <li class="breadcrumb-item"><a href="{% url 'admin:index' %}"><i class="fa fa-tachometer-alt"></i> {% trans 'Home' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a></li>
    <!-- <li class="breadcrumb-item">
        {% if has_view_permission %}
            <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
        {% else %}
            {{ opts.verbose_name_plural|capfirst }}
        {% endif %}
    </li> -->
    <li class="breadcrumb-item active">
        {% if add %}
            {% blocktrans with name=opts.verbose_name %}Add {{ name }}{% endblocktrans %}
        {% else %}
            {{ original|truncatewords:"18" }}
        {% endif %}
    </li>
</ol>

{% endblock %}

app/templates/success_redirect.html
Redirecting...

app/templates/top_navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #3e3e3e;">
    <div class="container">
        <a class="navbar-brand" href="#"><strong>BI Central</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link active" href="#">Home</a>
                <a class="nav-item nav-link" href="#">Reports</a>
                <a class="nav-item nav-link" href="#">FTP Repo</a>
                <a class="nav-item nav-link" href="#">About</a>
            </div>
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="#"><span class="fab fa-facebook-f"></span></a>
                <a class="nav-item nav-link" href="#"><span class="fab fa-twitter"></span></a>
                <a class="nav-item nav-link" href="#"><span class="fab fa-yahoo"></span></a>
            </div>
        </div>
    </div>
</nav>